services:
  - type: web
    name: emotion-suppression-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd Emotion-suppression-api/backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.12"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
