import os
import sys
import numpy as np
import torch
import torch.nn as nn
import pandas as pd

BASE_DIR = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
if BASE_DIR not in sys.path:
    sys.path.insert(0, BASE_DIR)

from emotion.detect_emotion import detect_emotions_from_video

from preprocessing.extract_au_openface import extract_aus
from preprocessing.build_feature_sequence import build_sequences

from speech.extract_audio import extract_audio
from speech.detect_speech_events import detect_speech_events
MODEL_PATH = os.path.join(BASE_DIR, "models", "suppression_model.pth")
TEMP_OUTPUT = os.path.join(BASE_DIR, "data", "temp_csv")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# LSTM model definition (same as training)
class SuppressionLSTM(nn.Module):
    def __init__(self, input_size):
        super().__init__()
        self.lstm = nn.LSTM(input_size, 64, batch_first=True)
        self.fc = nn.Linear(64, 1)

    def forward(self, x):
        _, (h, _) = self.lstm(x)
        return self.fc(h[-1])


def predict_video(video_path):

    import shutil

    # Clear previous temp CSVs
    if os.path.exists(TEMP_OUTPUT):
        shutil.rmtree(TEMP_OUTPUT)

    # 1-- Extract AU CSV
    os.makedirs(TEMP_OUTPUT, exist_ok=True)
    extract_aus(video_path, TEMP_OUTPUT)

    # Find generated CSV
    csv_files = [f for f in os.listdir(TEMP_OUTPUT) if f.endswith(".csv")]
    if not csv_files:
        raise Exception("No CSV generated by OpenFace")

    csv_path = os.path.join(TEMP_OUTPUT, csv_files[0])

    # 2-- Build sequences
    sequences = build_sequences(csv_path)

    # ---- Estimate AU-based emotion signals ----
    df = pd.read_csv(csv_path)

    au_cols = [col for col in df.columns if "_r" in col]
    au_means = df[au_cols].mean()

    emotion_scores = {
        "anger": au_means.get("AU04_r", 0) + au_means.get("AU07_r", 0) + au_means.get("AU23_r", 0),
        "sadness": au_means.get("AU01_r", 0) + au_means.get("AU04_r", 0) + au_means.get("AU15_r", 0),
        "fear": au_means.get("AU01_r", 0) + au_means.get("AU02_r", 0) + au_means.get("AU05_r", 0) + au_means.get("AU26_r", 0),
        "happiness": au_means.get("AU06_r", 0) + au_means.get("AU12_r", 0)
    }

    predicted_hidden_emotion = max(emotion_scores, key=emotion_scores.get)

    if len(sequences) == 0:
        raise Exception("Not enough frames for analysis")

    # 3️-- Load model
    model = SuppressionLSTM(sequences.shape[2]).to(device)
    model.load_state_dict(torch.load(MODEL_PATH, map_location=device))
    model.eval()

    # 4️-- Predict
    X = torch.tensor(sequences, dtype=torch.float32).to(device)
    X = torch.nan_to_num(X)

    with torch.no_grad():
        outputs = model(X)
        # Flatten outputs
        outputs = outputs.detach().cpu().numpy().flatten()

        # Approximate window time step (assume 30 fps)
        fps = 30
        window_size = 20
        time_per_window = window_size / fps  # ~0.67 sec

        # Time array for each window
        window_times = np.arange(len(outputs)) * time_per_window

        print("First 10 suppression window predictions:")
        print(outputs[:10])

    # 5️⃣ Final suppression index (raw)
    suppression_score = float(np.mean(outputs))

    # ---- Normalization using global dataset stats ----
    GLOBAL_MIN = 0.5191223 #p5
    GLOBAL_MAX = 5.066453 #p95

    normalized_score = (suppression_score - GLOBAL_MIN) / (GLOBAL_MAX - GLOBAL_MIN)
    normalized_score = max(0, min(1, normalized_score))  # clamp to [0,1]

    # ---- Level classification ----
    if normalized_score < 0.4:
        level = "Low Suppression"
    elif normalized_score < 0.7:
        level = "Moderate Suppression"
    else:
        level = "High Suppression"

    # ---- Emotion Detection ----
    emotion_data = detect_emotions_from_video(video_path)

    # Compute dominant emotion over video
    if len(emotion_data) > 0:
        avg_emotions = {}

        for frame_emotions in emotion_data:
            for k, v in frame_emotions.items():
                avg_emotions[k] = avg_emotions.get(k, 0) + v

        for k in avg_emotions:
            avg_emotions[k] /= len(emotion_data)

        dominant_emotion = max(avg_emotions, key=avg_emotions.get)
    else:
        dominant_emotion = None

    # ---- Speech Latency ----
    audio_path = os.path.join(BASE_DIR, "data", "temp_audio.wav")

    has_audio = extract_audio(video_path, audio_path)

    if has_audio:
        speech_segments, latency_events = detect_speech_events(audio_path)
        print("Speech Segments:", speech_segments)
        print("Latency Events:", latency_events)
    else:
        speech_segments = []
        latency_events = []
    
    # if speech_onset is not None:
    # # Only consider suppression before speech
    #     pre_speech_indices = window_times <= speech_onset

    #     if np.any(pre_speech_indices):
    #         pre_speech_outputs = outputs[pre_speech_indices]
    #         pre_speech_times = window_times[pre_speech_indices]

    #         baseline = np.mean(outputs)
    #         threshold = baseline + 0.5 * np.std(outputs)

    #         # Find indices above threshold
    #         spike_indices = np.where(pre_speech_outputs > threshold)[0]

    #         if len(spike_indices) > 0:
    #             first_spike = spike_indices[0]
    #             peak_time = pre_speech_times[first_spike]
    #             latency = speech_onset - peak_time
    #         else:
    #             peak_time = None
    #             latency = None
    #         print("Speech Onset Time:", speech_onset)
    #         print("Peak Suppression Time Before Speech:", peak_time if speech_onset is not None and np.any(pre_speech_indices) else None)

            
    #     else:
    #         latency = None
    # else:
    #     latency = None
    
    if level in ["Moderate Suppression", "High Suppression"] \
    and predicted_hidden_emotion is not None \
    and predicted_hidden_emotion != dominant_emotion:

        suppressed_emotion = predicted_hidden_emotion
    else:
        suppressed_emotion = None

    return suppression_score, normalized_score, level, \
       dominant_emotion, suppressed_emotion, \
       window_times, outputs, latency_events

if __name__ == "__main__":

    # test_video = r"G:\capstone data\CASME II\CASME2_Compressed video\CASME2_compressed\sub01\EP02_01f.avi"
    # test_video = os.path.join(BASE_DIR, "sample test", "sample_ravdess.mp4")
    test_video = os.path.join(BASE_DIR, "sample test", "EP02_01f.avi")


    raw_score, norm_score, level, \
    emotion, suppressed_emotion, \
    window_times, outputs, latency_events = predict_video(test_video)
    
    print("Dominant Visible Emotion:", emotion)
    print("Predicted Hidden Emotion:", suppressed_emotion)
    print("Raw Suppression Score:", raw_score)
    print("Normalized Score (0-1):", norm_score)
    print("Suppression Level:", level)
    print("Latency Events (start_time, duration):", latency_events)
    